name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * SUN'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MY_ENV_VAR
      
    
    
